/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Menkrep;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import static javafx.application.Application.launch;

//


public class App extends Application {
    public String getGreeting() {
        return "Hello world";
    }

//    public void start(Stage stage) {
//        Text text = new Text();
//        text.setText("Loading...");
//        text.setX(50);
//        text.setY(50);
//
//        Group root = new Group();
//        root.getChildren().add(text);
//
//        Scene scene = new Scene(root, 1280, 720);
//
//        stage.setTitle("Menkrep");
//        stage.setScene(scene);
//        stage.show();
//
//        text.setText("Menkrep card battle");
//    }

    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("GUI/scene.fxml"));
        Scene scene = new Scene(root);

        stage.setTitle("Menkrep");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
