/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Menkrep;

//import Menkrep.Model.Reference.Reference;
//
//import java.io.IOException;
//import java.net.URISyntaxException;


public class App {

    public static void main(String[] args){
//        try {
//            Reference kartuReference = new Reference();
//            System.out.println(kartuReference.getKarakter());
//        } catch (IOException | URISyntaxException e) {
//            System.out.println("Error");
//        }
        System.out.println("Hello world");
    }
}
