/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Menkrep;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test
    @DisplayName("App correct addition")
    public void appHasAddition() {
        App classUnderTest = new App();
        assertEquals(5, classUnderTest.penjumlahan(2,3));
    }
}
